"""add document file metadata

Revision ID: 87b92c802476
Revises: 28651558e365
Create Date: 2026-08-24 23:32:25.760691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b92c802476'
down_revision: Union[str, Sequence[str], None] = '28651558e365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_file_name', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=True)
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'stored_file_name')
    # ### end Alembic commands ###
