"""add document file name

Revision ID: b1df5bf93ed9
Revises: c1feec045776
Create Date: 2026-08-17 19:25:46.667410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1df5bf93ed9'
down_revision: Union[str, Sequence[str], None] = 'c1feec045776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_name', sa.String(length=225), nullable=True))
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))


    op.execute(
        "UPDATE documents SET description = '' "
        "WHERE description IS NULL"
    )

    op.alter_column(
        "documents",
        "description",
        nullable=False,
    )
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
