from datetime import datetime

from pydantic.v1 import Field
from sqlalchemy import DateTime, String, Text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.connection import Base


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True,
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    

    description: Mapped[str] = mapped_column(
        String(225),
        nullable=False,
    )
    # Original filename uploaded by the user
    file_name: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    # Filename generated by our application
    stored_file_name: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    # Physical/storage location of the file
    file_path: Mapped[str | None] = mapped_column(
        String(1000),
        nullable=True,
    )

    # MIME type, for example application/pdf
    mime_type: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    # File size in bytes
    file_size: Mapped[int | None] = mapped_column(
        nullable=True,
    )

    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="uploaded",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )
    user: Mapped["User"] = relationship(
        back_populates="documents"
    )


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True,
    )

    email: Mapped[str] = mapped_column(
            String(255),
            unique=True,
            nullable=False,
            index=True,
    )

    full_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    documents: Mapped[list["Document"]] = relationship(
        back_populates="user",
        cascade="all, delete-orphan",
    )